set(_CATKIN_CURRENT_PACKAGE "rewrite_imu_pkg")
set(rewrite_imu_pkg_VERSION "1.0.0")
set(rewrite_imu_pkg_MAINTAINER "menichea <menichea@ethz.ch>")
set(rewrite_imu_pkg_PACKAGE_FORMAT "2")
set(rewrite_imu_pkg_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(rewrite_imu_pkg_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(rewrite_imu_pkg_BUILDTOOL_DEPENDS "catkin")
set(rewrite_imu_pkg_BUILDTOOL_EXPORT_DEPENDS )
set(rewrite_imu_pkg_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(rewrite_imu_pkg_RUN_DEPENDS "roscpp" "sensor_msgs")
set(rewrite_imu_pkg_TEST_DEPENDS )
set(rewrite_imu_pkg_DOC_DEPENDS )
set(rewrite_imu_pkg_URL_WEBSITE "")
set(rewrite_imu_pkg_URL_BUGTRACKER "")
set(rewrite_imu_pkg_URL_REPOSITORY "")
set(rewrite_imu_pkg_DEPRECATED "")